[package]
name = "rsolver"
version = "1.0.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
csv = "1.1.1"
failure = "0.1.5"
mysql = "21.0.1"
pathfinding = "2.2.0"
rand = "0.8.3"
rusqlite = { version = "0.26", optional = true }
rust-ini = "0.17.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.19"

[features]
default = []
sqlite = ["rusqlite"]
