[package]
name = "rsolver"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
flexi_logger = "0.14.5"
log = "0.4.6"
mysql = "17.0.0"
pathfinding = "2.0.3"
rand = "0.7.2"
rusqlite = { version = "0.21.0", optional = true }
rust-ini = "0.13.0"
csv = "1.1.1"

[features]
default = []
sqlite = ["rusqlite"]
