[package]
name = "rsolver"
version = "1.0.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"

[dependencies]
anyhow = "1.0.52"
clap = "2.33.0"
csv = "1.1.1"
pathfinding = "2.2.0"
rand = "0.8.3"
rust-ini = "0.17.0"
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "mysql", "macros", "offline", "any"] }
tokio = { version = "1.13.0", features = ["full"] }
tracing = "0.1.26"
tracing-subscriber = "0.3"

[features]
default = []
sqlite = ["sqlx/sqlite"]
