[package]
name = "rsolver"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]

[dependencies]
clap = "2.24"
error-chain = "0.10.0"
flexi_logger = "0.5.2"
log = "0.3.0"
mysql = "11.1.2"
rand = "0.3"
rust-ini = "0.10"
