[package]
name = "rsolver"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]

[dependencies]
clap = "2.24"
error-chain = "0.11.0"
flexi_logger = "0.6.8"
log = "0.3.0"
mysql = "12.0.3"
rand = "0.3"
rust-ini = "0.10"
