[package]
name = "rsolver"
version = "1.0.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
csv = "1.1.1"
failure = "0.1.5"
flexi_logger = "0.17.1"
log = "0.4.6"
mysql = "20.1.0"
pathfinding = "2.0.3"
rand = "0.8.3"
rusqlite = { version = "0.25.1", optional = true }
rust-ini = "0.17.0"

[features]
default = []
sqlite = ["rusqlite"]
