[package]
name = "rsolver"
version = "1.0.0"
description = "Automatically assign projects to students"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"
license = "Apache-2.0/MIT"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.2", features = ["derive"] }
csv = "1.1.6"
pathfinding = "3.0.12"
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "mysql", "macros", "offline", "any"] }
tokio = { version = "1.18.2", features = ["full"] }
toml = "0.5.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"

[features]
default = []
sqlite = ["sqlx/sqlite"]
