[package]
name = "rsolver"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
flexi_logger = "0.11.4"
log = "0.4.6"
mysql = "16.0.1"
pathfinding = "1.1.12"
rand = "0.6.5"
rusqlite = { version = "0.18.0", optional = true }
rust-ini = "0.13.0"
csv = "1.1.1"

[features]
default = []
sqlite = ["rusqlite"]
