[package]
name = "rsolver"
version = "1.0.0"
description = "Automatically assign projects to students"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0", features = ["derive"] }
csv = "1.1.1"
pathfinding = "3.0.6"
rand = "0.8.3"
serde = { version = "1.0.133", features = ["derive"] }
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "mysql", "macros", "offline", "any"] }
tokio = { version = "1.13.0", features = ["full"] }
toml = "0.5.8"
tracing = "0.1.26"
tracing-subscriber = "0.3"

[features]
default = []
sqlite = ["sqlx/sqlite"]
