[package]
name = "rsolver"
version = "1.0.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"

[dependencies]
async-trait = "0.1.51"
clap = "2.33.0"
csv = "1.1.1"
failure = "0.1.5"
pathfinding = "2.2.0"
rand = "0.8.3"
rusqlite = { version = "0.26", optional = true }
rust-ini = "0.17.0"
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "mysql", "macros", "offline"] }
tokio = { version = "1.13.0", features = ["full"] }
tracing = "0.1.26"
tracing-subscriber = "0.3"

[features]
default = []
sqlite = ["rusqlite"]
