[package]
name = "rsolver"
version = "1.0.0"
description = "Automatically assign projects to students"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"
license = "Apache-2.0/MIT"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3", features = ["derive"] }
csv = "1.2.1"
pathfinding = "4.2.1"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "mysql", "macros", "offline", "any"] }
tokio = { version = "1.28.1", features = ["full"] }
toml = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[features]
default = []
sqlite = ["sqlx/sqlite"]
