[package]
name = "rsolver"
version = "1.0.0"
description = "Automatically assign projects to students"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"
license = "Apache-2.0/MIT"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
color-eyre = "0.6.2"
csv = "1.2.2"
eyre = "0.6.8"
pathfinding = "4.2.1"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio-rustls", "mysql", "macros", "any"] }
tokio = { version = "1.28.1", features = ["full"] }
toml = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[features]
default = []
sqlite = ["sqlx/sqlite"]
